# Numpy

In [72]:
import numpy as np;

In [73]:
my_arr = np.array([1,2,3,4])
print(my_arr)
type(my_arr)

[1 2 3 4]


numpy.ndarray

In [74]:
np.zeros(4) #zero array

array([0., 0., 0., 0.])

In [75]:
np.ones(4) #one array

array([1., 1., 1., 1.])

In [76]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
np.arange(0,10) # arrange function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.arange(0,10,2) # including gap

array([0, 2, 4, 6, 8])

In [79]:
np.linspace(0,10,5) # last perameter denote numbers of element

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [80]:
np.random.rand(5, 5)

array([[0.9485834 , 0.78357682, 0.27808965, 0.04315049, 0.39279043],
       [0.55641722, 0.11323285, 0.83459183, 0.36495933, 0.63281174],
       [0.57188357, 0.30125322, 0.98387755, 0.26457112, 0.28536319],
       [0.03559877, 0.73511589, 0.19486963, 0.89771458, 0.48210977],
       [0.31377453, 0.51301944, 0.59883865, 0.38471523, 0.40811733]])

In [81]:
np.random.randn(3,3)

array([[-0.38583331,  0.09319322, -0.37056267],
       [ 0.59131463,  1.1691162 ,  0.21495627],
       [ 0.35785271,  0.48843337,  0.1841118 ]])

In [82]:
np.random.randint(1,10,5)

array([2, 6, 1, 8, 6], dtype=int32)

# Array Methods

In [83]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [84]:
arr.shape

(10,)

In [85]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [86]:
arr.max()

np.int64(10)

In [87]:
arr.min()

np.int64(1)

In [88]:
arr.argmax() # max value index

np.int64(9)

In [89]:
arr.argmin()

np.int64(0)

# Array Attributes

In [90]:
a = np.arange(21)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [91]:
a.size

21

In [92]:
a.ndim 

1

In [93]:
a.dtype

dtype('int64')

In [94]:
a.itemsize

8

# indexing & slicing

In [95]:
ar = np.arange(0,11)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [96]:
ar[3]

np.int64(3)

In [97]:
ar[2:6]

array([2, 3, 4, 5])

In [98]:
ar[2:11:2]

array([ 2,  4,  6,  8, 10])

In [99]:
ar_copy = ar.copy()
ar_copy[2]=4
ar_copy


array([ 0,  1,  4,  3,  4,  5,  6,  7,  8,  9, 10])

# operation

In [100]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
array + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [102]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
array/array

C:\Users\shuvo\AppData\Local\Temp\ipykernel_20924\2541472222.py:1: RuntimeWarning: invalid value encountered in divide
  array/array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [104]:
array.sum()

np.int64(55)

In [105]:
array.mean()

np.float64(5.0)

In [106]:
array.var()

np.float64(10.0)

In [107]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [108]:
np.log(array)

C:\Users\shuvo\AppData\Local\Temp\ipykernel_20924\3382134483.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [109]:
arr = np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [110]:
arr.shape

(5, 5)

In [111]:
arr.sum()

np.int64(300)

In [112]:
arr.sum(axis=0) # row

array([50, 55, 60, 65, 70])

In [113]:
arr.sum(axis=1) # column

array([ 10,  35,  60,  85, 110])

# file handling

In [115]:
data = np.loadtxt('numeric_data.csv', delimiter=',')
data

array([[ 1., 85., 78., 92.],
       [ 2., 76., 88., 80.],
       [ 3., 90., 91., 89.],
       [ 4., 65., 70., 72.],
       [ 5., 88., 84., 90.]])