# Numpy

In [2]:
import numpy as np;

In [3]:
my_arr = np.array([1,2,3,4])
print(my_arr)
type(my_arr)

[1 2 3 4]


numpy.ndarray

In [4]:
np.zeros(4) #zero array

array([0., 0., 0., 0.])

In [5]:
np.ones(4) #one array

array([1., 1., 1., 1.])

In [6]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.arange(0,10) # arrange function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2) # including gap

array([0, 2, 4, 6, 8])

In [9]:
np.linspace(0,10,5) # last perameter denote numbers of element

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
np.random.rand(5, 5)

array([[0.64387178, 0.85097764, 0.94157123, 0.22723483, 0.81322058],
       [0.06717811, 0.66733313, 0.67851937, 0.94105782, 0.38981822],
       [0.77042636, 0.52932381, 0.96975265, 0.86180129, 0.06268673],
       [0.42158787, 0.20610963, 0.93453828, 0.29335003, 0.51524946],
       [0.93596244, 0.23598205, 0.73383496, 0.47396072, 0.4409604 ]])

In [19]:
np.random.randn(3,3)

array([[-0.52502523,  1.67570314, -1.23486501],
       [ 0.73358285,  0.53462882,  1.85018842],
       [ 0.36259516,  0.66383024,  0.82101741]])

In [20]:
np.random.randint(1,10,5)

array([2, 6, 3, 7, 7], dtype=int32)