# Numpy

In [1]:
import numpy as np;

In [2]:
my_arr = np.array([1,2,3,4])
print(my_arr)
type(my_arr)

[1 2 3 4]


numpy.ndarray

In [3]:
np.zeros(4) #zero array

array([0., 0., 0., 0.])

In [4]:
np.ones(4) #one array

array([1., 1., 1., 1.])

In [5]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.arange(0,10) # arrange function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2) # including gap

array([0, 2, 4, 6, 8])

In [8]:
np.linspace(0,10,5) # last perameter denote numbers of element

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
np.random.rand(5, 5)

array([[0.11776639, 0.84029197, 0.39551477, 0.02268852, 0.40183294],
       [0.67816127, 0.1408128 , 0.6464563 , 0.14429308, 0.63629891],
       [0.26915889, 0.13166292, 0.05024781, 0.11212641, 0.60886097],
       [0.75664886, 0.86900836, 0.80055323, 0.60719698, 0.42575575],
       [0.82287226, 0.58212544, 0.43146793, 0.52616967, 0.3046575 ]])

In [10]:
np.random.randn(3,3)

array([[-0.48840169, -0.85833552, -0.32162773],
       [ 0.74021581,  2.02685926, -0.11738803],
       [ 0.27876653,  0.28170266, -0.37924775]])

In [11]:
np.random.randint(1,10,5)

array([4, 7, 9, 9, 7], dtype=int32)

# Array Methods

In [12]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
arr.shape

(10,)

In [14]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
arr.max()

np.int64(10)

In [16]:
arr.min()

np.int64(1)

In [17]:
arr.argmax() # max value index

np.int64(9)

In [18]:
arr.argmin()

np.int64(0)

# Array Attributes

In [19]:
a = np.arange(21)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [20]:
a.size

21

In [21]:
a.ndim 

1

In [22]:
a.dtype

dtype('int64')

In [23]:
a.itemsize

8

# indexing & slicing

In [24]:
ar = np.arange(0,11)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [25]:
ar[3]

np.int64(3)

In [26]:
ar[2:6]

array([2, 3, 4, 5])

In [27]:
ar[2:11:2]

array([ 2,  4,  6,  8, 10])

In [28]:
ar_copy = ar.copy()
ar_copy[2]=4
ar_copy


array([ 0,  1,  4,  3,  4,  5,  6,  7,  8,  9, 10])

# operation

In [29]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
array + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
array/array

C:\Users\shuvo\AppData\Local\Temp\ipykernel_17104\2541472222.py:1: RuntimeWarning: invalid value encountered in divide
  array/array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [33]:
array.sum()

np.int64(55)

In [34]:
array.mean()

np.float64(5.0)

In [35]:
array.var()

np.float64(10.0)

In [36]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [37]:
np.log(array)

C:\Users\shuvo\AppData\Local\Temp\ipykernel_17104\3382134483.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [38]:
arr = np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.shape

(5, 5)

In [40]:
arr.sum()

np.int64(300)

In [41]:
arr.sum(axis=0) # row

array([50, 55, 60, 65, 70])

In [42]:
arr.sum(axis=1) # column

array([ 10,  35,  60,  85, 110])

# file handling

In [43]:
data = np.loadtxt('numeric_data.csv', delimiter=',')
data

array([[ 1., 85., 78., 92.],
       [ 2., 76., 88., 80.],
       [ 3., 90., 91., 89.],
       [ 4., 65., 70., 72.],
       [ 5., 88., 84., 90.]])

# pandas

In [44]:
import pandas as pd
import numpy as np

In [45]:
index = 'r1 r2 r3 r4 r5 r6 r7 r8 r9 r10'.split()
coloms = 'c1 c2 c3 c4 c5 c6 c7 c8 c9 c10'.split()

In [46]:
index

['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10']

In [47]:
coloms

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']

In [48]:
array_2d = np.arange(0,100).reshape(10,10)
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
df = pd.DataFrame(data=array_2d,columns=coloms,index=index)
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [50]:
df.c1

r1      0
r2     10
r3     20
r4     30
r5     40
r6     50
r7     60
r8     70
r9     80
r10    90
Name: c1, dtype: int64

In [51]:
df.loc['r1']

c1     0
c2     1
c3     2
c4     3
c5     4
c6     5
c7     6
c8     7
c9     8
c10    9
Name: r1, dtype: int64

In [52]:
df.loc[['r1','r2']] # multiple 

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1   0   1   2   3   4   5   6   7   8    9
r2  10  11  12  13  14  15  16  17  18   19

In [53]:
df.iloc[1] # access using index

c1     10
c2     11
c3     12
c4     13
c5     14
c6     15
c7     16
c8     17
c9     18
c10    19
Name: r2, dtype: int64

In [54]:
df['c11']='A'
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10 c11
r1    0   1   2   3   4   5   6   7   8    9   A
r2   10  11  12  13  14  15  16  17  18   19   A
r3   20  21  22  23  24  25  26  27  28   29   A
r4   30  31  32  33  34  35  36  37  38   39   A
r5   40  41  42  43  44  45  46  47  48   49   A
r6   50  51  52  53  54  55  56  57  58   59   A
r7   60  61  62  63  64  65  66  67  68   69   A
r8   70  71  72  73  74  75  76  77  78   79   A
r9   80  81  82  83  84  85  86  87  88   89   A
r10  90  91  92  93  94  95  96  97  98   99   A

In [55]:
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10 c11
r1    0   1   2   3   4   5   6   7   8    9   A
r2   10  11  12  13  14  15  16  17  18   19   A
r3   20  21  22  23  24  25  26  27  28   29   A
r4   30  31  32  33  34  35  36  37  38   39   A
r5   40  41  42  43  44  45  46  47  48   49   A
r6   50  51  52  53  54  55  56  57  58   59   A
r7   60  61  62  63  64  65  66  67  68   69   A
r8   70  71  72  73  74  75  76  77  78   79   A
r9   80  81  82  83  84  85  86  87  88   89   A
r10  90  91  92  93  94  95  96  97  98   99   A

In [56]:
df.drop('c7',axis=1) # temporary delete


c1  c2  c3  c4  c5  c6  c8  c9  c10 c11
r1    0   1   2   3   4   5   7   8    9   A
r2   10  11  12  13  14  15  17  18   19   A
r3   20  21  22  23  24  25  27  28   29   A
r4   30  31  32  33  34  35  37  38   39   A
r5   40  41  42  43  44  45  47  48   49   A
r6   50  51  52  53  54  55  57  58   59   A
r7   60  61  62  63  64  65  67  68   69   A
r8   70  71  72  73  74  75  77  78   79   A
r9   80  81  82  83  84  85  87  88   89   A
r10  90  91  92  93  94  95  97  98   99   A

In [68]:
df.drop('c11', axis=1,inplace=True)


In [70]:
bool_mask = df > 10
bool_mask

c1     c2     c3     c4     c5     c6     c7     c8     c9    c10
r1   False  False  False  False  False  False  False  False  False  False
r2   False   True   True   True   True   True   True   True   True   True
r3    True   True   True   True   True   True   True   True   True   True
r4    True   True   True   True   True   True   True   True   True   True
r5    True   True   True   True   True   True   True   True   True   True
r6    True   True   True   True   True   True   True   True   True   True
r7    True   True   True   True   True   True   True   True   True   True
r8    True   True   True   True   True   True   True   True   True   True
r9    True   True   True   True   True   True   True   True   True   True
r10   True   True   True   True   True   True   True   True   True   True

In [ ]:
df[df>20]

c1    c2    c3    c4    c5    c6    c7    c8
r1    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
r2    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
r3    NaN  21.0  22.0  23.0  24.0  25.0  26.0  27.0
r4   30.0  31.0  32.0  33.0  34.0  35.0  36.0  37.0
r5   40.0  41.0  42.0  43.0  44.0  45.0  46.0  47.0
r6   50.0  51.0  52.0  53.0  54.0  55.0  56.0  57.0
r7   60.0  61.0  62.0  63.0  64.0  65.0  66.0  67.0
r8   70.0  71.0  72.0  73.0  74.0  75.0  76.0  77.0
r9   80.0  81.0  82.0  83.0  84.0  85.0  86.0  87.0
r10  90.0  91.0  92.0  93.0  94.0  95.0  96.0  97.0